# After changing this file, run it through http://lint.travis-ci.org/
# Generates 4 builds, the ones for python3 will install external wheels
language: python
python:
  - 2.6
  - 2.7
matrix:
  include:
    - python: 3.2
      env:
        - NUMPYSPEC===1.7.1
    - python: 3.3
      env:
        - NUMPYSPEC===1.8.0
before_install:
  - sudo add-apt-repository -y ppa:biometrics/bob
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev libblitz1-dev
  - test -n "${NUMPYSPEC}" && sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - test -n "${NUMPYSPEC}" && pip install --upgrade pip setuptools #new wheel support
  - test -n "${NUMPYSPEC}" && pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel --use-mirrors numpy$NUMPYSPEC sphinx nose
  - python -V
install:
  - "python bootstrap.py"
  - "./bin/buildout"
script:
  - "./bin/nosetests -sv"
  - "./bin/sphinx-build -b doctest doc sphinx"
  - "./bin/sphinx-build -b html doc sphinx"
